# Configuration file
# DO NOT EDIT!

DEBUG = True
VERBOSE = False

EXTRA_DEBUG = False # CAUTION: IT BROKS ALL COMMANDLINE EXCEPTION SECURITY! YOU WILL GET UNSTABLE CONSOLE, IF SOME MODULE AND/OR FUNCTION WORKS INCORRECTLY!

# Exit values

SYS_EXEC_STOP = 1
SYS_EXEC_CONTINUE = 0
SYS_EXEC_CMD_NFOUND = 127 # From bash)
SYS_EXEC_EXECFILE = 3 # Load file commandly
SYS_MODULE_LOAD = 6
SYS_MODULE_UNLOAD = 7
SYS_FUNCTION_LOAD = 8
SYS_FUNCTION_UNLOAD = 9
SYS_FUNCTION_SETUP = 10
SYS_EXEC_FORCESTOP = 4 # Need for file execution
SHELL_VARS_EXPORT = 5

# Other

DEFAULT_LANG = "en"
DEFAULT_TOKENIZER = "bash"
DEFAULT_MODULES = ["bash_like", "unix_like"]
DEFAULT_UNLOADS_FUNC = []

# Version

MAJOR_VER = 2
MINOR_VER = 0
PATCH_VER = 10
RELEASE_VER = "alpha1"
SALT = "general"
